board:
  dir: up                   # アップロードするディレクトリ DocumentRoor配下に作成 パーミッション777
  maxsize: 2                # アップロード最大サイズ(MB)
  maxfiles: 5000            # 最大ファイル数
  type: image               # 許可するmimetypeのtype image/jpegならimageを指定する,カンマ区切り
  ext: gif,jpg,png,bmp,jpeg # 許可する拡張子,カンマ区切り
  thumbnail:                # サムネイル
    dir: thumbnail          # 保存ディレクトリ
    width: 400              # 横 できれば縦横同じ大きさ
    height: 400             # 縦
  mosaic: 1                 # 保存ディレクトリ・縦・横はサムネイル共通
  pagination:
    per_page: 100           # 1ページあたりの数(デフォルト)
  key: desushiosushi        # ハッシュ用(変更すること)
  del: qwer					# デフォルト削除パス(変更すること) 削除キーがないものは全てこれで削除できる
admin:
  id: admin        #変更すること
  uass: qwer       #変更すること
  email: ahumau_nejitu@icloud.com #管理者メール
