board:
  dir: up              #アップロードするディレクトリ DocumentRoor配下に作成 パーミッション777
  thumbnail: thumbnail #サムネイルディレクトリ
  maxsize: 2           #アップロード最大サイズ(MB)
  maxfiles: 5000       #最大ファイル数
  type: image          #許可するmimetypeのtype image/jpegならimageを指定する,カンマ区切り
  ext: gif,jpg,png,bmp #許可する拡張子,カンマ区切り
  pad: 5               #ゼロパディングする数字
admin:
  id: admin        #変更すること
  uass: qwer       #変更すること
  email: ahumau_nejitu@icloud.com #管理者メール
